/** Runtime-neutral object storage port. Keys are generated by the domain, never by a caller. */
export interface BlobStore {
  ping(): Promise<void>
  capacity(): Promise<{ dataFreeBytes: number; metadataFreeBytes: number }>
  list(
    cursor?: string,
  ): Promise<{ items: { key: string; size: number }[]; nextCursor: string | null }>
  put(key: string, stream: ReadableStream<Uint8Array>, signal?: AbortSignal): Promise<number>
  stat(key: string): Promise<{ size: number } | null>
  read(key: string, start?: number, end?: number): ReadableStream<Uint8Array>
  delete(key: string): Promise<void>
}
