#!/usr/bin/env bun
/**
 * Writes src/scripts/icons.js from the Lucide icons listed in icons.list.
 *
 *   bun design/prototype/tools/gen-icons.mjs <dir of an unpacked lucide-static package>
 *
 * Lucide is ISC licensed (https://lucide.dev). The version is read from the package and written
 * into the generated file. The icon set the spec asks for is Lucide, stroke 1.75 (docs/02 section 8).
 */
import { join } from 'node:path'

const pkgDir = process.argv[2]
if (!pkgDir) {
  console.error('usage: gen-icons.mjs <lucide-static package dir>')
  process.exit(2)
}
const nodes = await Bun.file(join(pkgDir, 'icon-nodes.json')).json()
const version = (await Bun.file(join(pkgDir, 'package.json')).json()).version
const list = (await Bun.file(join(import.meta.dir, 'icons.list')).text())
  .split('\n')
  .map((line) => line.trim())
  .filter((line) => line && !line.startsWith('#'))

const missing = list.filter((name) => !nodes[name])
if (missing.length > 0) {
  console.error(`not in lucide-static ${version}: ${missing.join(', ')}`)
  process.exit(1)
}

const body = list.map((name) => `  '${name}': ${JSON.stringify(nodes[name])},`).join('\n')

const out = `// Generated by tools/gen-icons.mjs from lucide-static ${version} (ISC license, https://lucide.dev).
// Do not edit by hand; change tools/icons.list and regenerate.
// Each icon is a list of [tag, attributes] on a 24 x 24 grid.
export const LUCIDE = {
${body}
}
export const LUCIDE_VERSION = '${version}'
`
await Bun.write(join(import.meta.dir, '..', 'src', 'scripts', 'icons.generated.js'), out)
console.log(`wrote ${list.length} icons from lucide-static ${version}`)
