# Generated by Django 4.1.13 on 2025-01-15 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='聊天室名称')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('public', '公共聊天室'), ('private', '私密聊天室')], default='public', max_length=10, verbose_name='聊天室类型')),
                ('password', models.CharField(blank=True, max_length=4, null=True, verbose_name='访问密码')),
                ('icon', models.ImageField(default='room_icons/default.png', upload_to='room_icons/', verbose_name='聊天室图标')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频'), ('file', '文件'), ('recall', '撤回提示')], default='text', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_recalled', models.BooleanField(default=False)),
                ('recall_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_chats', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('initiator', 'receiver', 'created_at')},
            },
        ),
        migrations.AddConstraint(
            model_name='onlineuser',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_online_user'),
        ),
    ]
