# Generated by Django 4.1.13 on 2025-01-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
        ('chat', '0003_privatechat_onlineuser'),
    ]

    operations = [
    ]
