/**
 * Configures the local Garage node (safe to run repeatedly):
 * 1. assigns the single-node layout, 2. imports the S3 key from .env.local,
 * 3. creates the dev and test buckets and grants the key access to them.
 * Secrets are passed to the Garage CLI but never printed.
 */
import { $ } from 'bun'
import { getEnv, isUnset, readEnvFile } from './lib/env-file.ts'

const KEY_NAME = 'chatapp-dev'
const env = await readEnvFile('.env.local')

function required(key: string): string {
  const value = getEnv(env, key)
  if (value === undefined || isUnset(value)) {
    console.error(`${key} is missing in .env.local: run \`bun run setup\` first`)
    process.exit(1)
  }
  return value
}

const keyId = required('S3_ACCESS_KEY_ID')
const secretKey = required('S3_SECRET_ACCESS_KEY')
const buckets = [required('S3_BUCKET'), required('S3_BUCKET_TEST')]

async function garage(args: string[]): Promise<{ ok: boolean; out: string; err: string }> {
  const result =
    await $`docker compose -f infra/compose.dev.yml --env-file .env.local exec -T garage /garage ${args}`
      .quiet()
      .nothrow()
  return {
    ok: result.exitCode === 0,
    out: result.stdout.toString(),
    err: result.stderr.toString(),
  }
}

async function mustRun(args: string[], label: string): Promise<string> {
  const result = await garage(args)
  if (!result.ok) {
    console.error(`garage ${label} failed:\n${result.err.trim()}`)
    process.exit(1)
  }
  return result.out
}

// 1. Layout: one node, zone dc1, 5 GB of capacity.
const layout = await mustRun(['layout', 'show'], 'layout show')
const layoutVersion = Number(/Current cluster layout version:\s*(\d+)/.exec(layout)?.[1] ?? '0')
if (layoutVersion === 0) {
  const nodeId = (await mustRun(['node', 'id', '-q'], 'node id')).trim().split('@')[0]
  if (!nodeId) {
    console.error('could not read the Garage node id')
    process.exit(1)
  }
  await mustRun(['layout', 'assign', '-z', 'dc1', '-c', '5G', nodeId], 'layout assign')
  await mustRun(['layout', 'apply', '--version', '1'], 'layout apply')
  console.log('layout: assigned and applied (version 1)')
} else {
  console.log(`layout: already applied (version ${layoutVersion})`)
}

// 2. Access key (generated by `bun run setup`, imported so it stays stable across resets).
if ((await garage(['key', 'info', keyId])).ok) {
  console.log(`key: ${KEY_NAME} present`)
} else {
  await mustRun(['key', 'import', '--yes', '-n', KEY_NAME, keyId, secretKey], 'key import')
  console.log(`key: ${KEY_NAME} imported`)
}

// 3. Buckets and permissions.
for (const bucket of buckets) {
  if ((await garage(['bucket', 'info', bucket])).ok) {
    console.log(`bucket: ${bucket} present`)
  } else {
    await mustRun(['bucket', 'create', bucket], `bucket create ${bucket}`)
    console.log(`bucket: ${bucket} created`)
  }
  await mustRun(
    ['bucket', 'allow', '--read', '--write', '--owner', bucket, '--key', keyId],
    `bucket allow ${bucket}`,
  )
}

console.log('garage: ready')
